"""Add rating, feedback and stripe_customer_id

Revision ID: cc5983a6ed71
Revises: b06f2fe44393
Create Date: 2026-06-04 11:52:24.351624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5983a6ed71'
down_revision: Union[str, Sequence[str], None] = 'b06f2fe44393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_requests', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('review_requests', sa.Column('feedback', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'stripe_customer_id')
    op.drop_column('review_requests', 'feedback')
    op.drop_column('review_requests', 'rating')
    # ### end Alembic commands ###
